### ISSUE TITLE
Eligibility of High Schoolers

### ISSUE THREAD

**Issue by StephenOrJames** [Women-in-Computing-at-RIT/wichacks.io#55]
I noticed that d6c1466 suggested that high schoolers can now apply, but [the eligibility section](https://github.com/Women-in-Computing-at-RIT/wichacks.io/blob/d6c146670128d239426946464080d3f6653faf15/app/views/pages/home.html.erb#L79-L80) wasn't updated to reflect that. An oversight, I assume?

**Comment by sman591** [comment]
Aha, definitely an oversight - thank you for catching that!
